Feat/noti
PoolC/Dialga pull request #124
Opened 2024-07-30 11:57 UTC by Hys-Lee

수정해주신 부분 다 살려서 진행했습니다

일단 undefined경우 처리를 간단하게 했는데, 이렇게 하는게 괜찮을지 모르겟네용

post동작은 useAppMutation을 썼습니다.

2024-07-31 01:25 UTC, jinoov requested changes

2024-07-31 01:25 UTC, jinoov commented on apps/web-client/src/components/header/Notification/Notification.tsx
> +    (data?.unreadCount ?? 0) > 0
65번째 라인에서 `assert(data, 'data is undefined');`라고 data가 무조건 존재한다고 assertion 매겨놨기 때문에(useQuery쪽에서 initialData가 있으므로)

`data?.~~` 이런 식으로 optional chaining은 사용하지 않아도 될 것 같아요

2024-07-31 01:25 UTC, jinoov commented on apps/web-client/src/components/header/Notification/Notification.tsx
> +                updateNotiReadStatus({ notificationId: dataOne.notificationId! });
post 호출한 다음에 unread 응답 다시 불러오는게 좋을 것 같아요
안 그러면 read했는데도 화면상으로는 unread 상태로 계속 남아있을거라서요.

이런식으로 개선되면 좋을 것 같습니다.

```tsx
const queryClient = useQueryClient()

// ...

updateNotiReadStatus({ notificationId: dataOne.notificationId! }, {
    onSuccess() {
        queryClient.invalidateQueries(queryKey.notification.unread)
    }
});
```

2024-07-31 01:58 UTC, Hys-Lee commented on apps/web-client/src/components/header/Notification/Notification.tsx
> +    (data?.unreadCount ?? 0) > 0
아하 알겠습니닷

2024-07-31 01:58 UTC, Hys-Lee commented on apps/web-client/src/components/header/Notification/Notification.tsx
> +                updateNotiReadStatus({ notificationId: dataOne.notificationId! });
아 맞네요. 
수정하겠습니다

2024-08-01 01:43 UTC, Hys-Lee commented
pr 수정 했습니다!

2024-08-01 09:13 UTC, merged